name: Build and push to ECR

on:
  workflow_call:
    inputs:
      aws_account_id:
        description: 'The account ID of the environment'
        required: true
        type: string
      aws_region:
        description: 'Region AWS'
        default: 'eu-west-1'
        required: false
        type: string
      docker_image_name:
        description: 'The docker image name'
        required: true
        type: string
      docker_context:
        description: 'The docker build context'
        required: true
        type: string
    secrets:
      aws_access_key_id:
        description: 'AWS access key id'
        required: true
      aws_secret_access_key:
        description: 'AWS secret access key'
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ inputs.aws_region }}
      - 
        name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.6.1
        with:
          push: true
          tags: |
            ${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/${{ inputs.docker_image_name }}:latest
            ${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/${{ inputs.docker_image_name }}:${{ github.sha }}
          context: ${{ inputs.docker_context }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}